[package]
name = "monkey-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "monkey_macros"
proc-macro = true
path = "src/lib.rs"

[dependencies]
quote = "1.0.28"
syn = "2.0.18"